apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: goapp

images:
- name: goapp
  newName: jcfalves/argocd-fullcycle
  newTag: f63b216a747e3c7d0b61bbec180b95e59a3c514d
