apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: goapp

images:
- name: goapp
  newName: jcfalves/argocd-fullcycle
  newTag: f6ad1c33b92bfda7f62cbfd21c096b286b29853a
