apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: goapp

images:
- name: goapp
  newName: jcfalves/argocd-fullcycle
  newTag: 13280ac15d530c40f0c60a0db67d8c74df2c6910
