name: CD
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: jcfalves/argocd-fullcycle:${{ github.sha }}, jcfalves/argocd-fullcycle:latest

  deploy:
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize_version: v3.6.1

      - name: update k8s
        run: |
          cd k8s
          kustomize edit set image goapp=jcfalves/argocd-fullcycle:${{ github.sha }}
          cat kustomization.yaml

      - name: commit
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git commit -am "Update k8s image to jcfalves/argocd-fullcycle:${{ github.sha }}"

      - name: push
        uses: ad-m/github-push-action@master
        #with:
        #  github_token: ${ { secrets.GITHUB_TOKEN }}
         # branch: main

     # - name: push
     #   uses: ad-m/github-push-action@master
        #with:
         # github_token: ${ { secrets.GITHUB_TOKEN }}
         # branch: main    

      #- name: Deploy to Kubernetes
      #  uses: imranismail/kubectl-kustomize-action@v1.0.0
      #  with:
      #    kubeconfig: ${ { secrets.KUBECONFIG }}
      #    kustomize_path: ./k8s   
